### ISSUE TITLE
NameError: name 'activation_function' is not defined

### ISSUE THREAD

**Issue by s348ankit** [amansrivastava17/siamese-text-similarity#1]
Getting Error Activation_function not Defined while trying to run below code

siamese = SiameseBiLSTM(CONFIG.embedding_dim , CONFIG.max_sequence_length, CONFIG.number_lstm_units , CONFIG.number_dense_units, CONFIG.rate_drop_lstm, CONFIG.rate_drop_dense, CONFIG.activation_function, CONFIG.validation_split_ratio)

best_model_path = siamese.train_model(sentences_pair, is_similar, embedding_meta_data, model_save_directory='./')

**Comment by ghost** [comment]
@s348ankit I think the problem is in model.py line 28 try changing `self.activation_function = activation_function` to  `self.activation_function = hidden_activation`

**Comment by amansrivastava17** [comment]
@johnkjoseph Thanks again john, fixed the issue.
