### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by BATspock** [amansrivastava17/siamese-text-similarity#2]
Traceback (most recent call last):
  File "lstm-siamese-text-similarity/controller.py", line 64, in <module>
    best_model_path = siamese.train_model(sentences_pair, is_similar, embedding_meta_data)
  File "lstm-siamese-text-similarity/model.py", line 49, in train_model
    tokenizer, embedding_matrix = embedding_meta_data['tokenizer'], embedding_meta_data['embedding_matrix']
TypeError: list indices must be integers or slices, not str

I get the following error, I am unable to debug

**Comment by ghost** [comment]
@BATspock Try taking out the last parameter in controller line number 64. It should be like this `best_model_path = siamese.train_model(sentences_pair, is_similar, embedding_meta_data)`

**Comment by BATspock** [comment]
@johnkjoseph I thought the same and removed the last parameter, still got the same error

**Comment by ghost** [comment]
@BATspock You are right, that doesn't matter, the problem is in model.py line number 32. The first parameter there should be self like this `def train_model(self, sentences_pair, is_similar, embedding_meta_data, model_save_directory='./'):`

**Comment by amansrivastava17** [comment]
@johnkjoseph Thanks for finding the bug. Have fixed.

**Comment by BATspock** [comment]
thanks a lot
