### ISSUE TITLE
AttributeError: 'Tokenizer' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by wakamd** [amansrivastava17/siamese-text-similarity#7]
I am using python 3.6, and keep getting this error:
elif x.ndim == 1:
AttributeError: 'Tokenizer' object has no attribute 'ndim'
Any help on resolving this. Tried searching the net did not help.
Regards

**Comment by amansrivastava17** [comment]
@wakamd  can you send me the screenshot at amans.rlx@gmail.com. 
I have run the controller.py, didn't found any error as such.

**Comment by wakamd** [comment]
Hi.
I used python 3.6 and got no errors.
Regards
